### ISSUE TITLE
Getting error while exec()ing ffmpeg - how to debug?

### ISSUE THREAD

**Issue by fionnb** [TechShreyash/AniDL#3]
Latest version from this git, naturally.

This is the output I get:

```
>> Downloading Episode 1 - 720p
>> Getting Download Links
----------------------------------------------------------------------------------------
|  Chunks Downloaded  |  Chunks/sec  |  Size Downloaded  |     Speed     |  Time Left  |
----------------------------------------------------------------------------------------
|       349/351       |   5 Chunks   |       357 MB      |   5.19 MB/s   |   0.01 min  |
----------------------------------------------------------------------------------------
>> Episode 1 - 720p Downloaded

>> Converting To Mp4
Failed To Download Episode 1
>> Error:  invalid literal for int() with base 10: "ffmpeg version n6.1.1 Copyright (c) 2000-2023 the FFmpeg developers\n  built with gcc 13.2.1 (GCC) 20230801\n  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enab
```

**Comment by fionnb** [comment]
This is the real traceback:
```
Traceback (most recent call last):
File "AniDL/./AniDl.py", line 150, in StartDownload
ConvertTsToMp4(filepath)
File "AniDL/Utils/FFmpeg.py", line 34, in ConvertTsToMp4
TOTAL_FRAMES += get_total_frames("./Downloads/temp/" + i)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "AniDL/Utils/FFmpeg.py", line 25, in get_total_frames
return int(x)
^^^^^^
```

**Comment by TechShreyash** [comment]
this is maybe because of a different version

if you are on windows use this https://drive.google.com/file/d/1jaE4SFombXVXvLsaRtU0siQFTF7F3hL0/view?usp=sharing

**Comment by TechShreyash** [comment]
ffmpeg -version

![image](https://github.com/TechShreyash/AniDL/assets/82265247/433b5b8b-c375-441e-b825-a43713efa08a)

**Comment by fionnb** [comment]
Actually it seems I got a video file with missing frame count in its metadata - so no "frame" in the ffmpeg info output. While developing a fix for such files, involving "manual" frame count using "ffprobe", the [search api server went missing](https://github.com/TechShreyash/AniDL/issues/4)  ;-)
I'll continue later.
